---
apiVersion: v1
kind: Namespace
metadata:
  name: called-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: called-service
  namespace: called-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: called-service
  template:
    metadata:
      labels:
        app: called-service
    spec:
      containers:
      - name: my-service
        image: flask-time-service:latest
        imagePullPolicy: Never
        args: ["--port", "9000"]
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: called-service
  namespace: called-service
spec:
  type: ClusterIP
  selector:
    app: called-service
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
