apiVersion: v1
kind: Namespace
metadata:
  name: service1-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service1
  namespace: service1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-service1
  template:
    metadata:
      labels:
        app: app-service1
    spec:
      containers:
      - name: app-service
        image: ubaidsh/app-service
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 9090
          name: metrics
        args:
        - "--app-port=5000"
        - "--metrics-port=9090"

---
apiVersion: v1
kind: Service
metadata:
  name: app-service1
  namespace: service1-ns
spec:
  selector:
    app: app-service1
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  type: ClusterIP