apiVersion: v1
kind: Namespace
metadata:
  name: otel-sender
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel-sender
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      attributes/environment:
        actions:
          - key: env
            value: prod
            action: insert
          - key: region
            value: us-west-2
            action: insert
          - key: namespace
            value: otel-sender
            action: insert

    exporters:
      otlp/chronosphere:
        endpoint: otel-collector-printer.otel-printer:4317
        tls:
          insecure: true

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch, attributes/environment]
          exporters: [otlp/chronosphere]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-sender
  namespace: otel-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-sender
  template:
    metadata:
      labels:
        app: otel-collector-sender
    spec:
      containers:
      - name: otel-collector-sender
        image: otel/opentelemetry-collector:0.88.0
        args:
        - "--config=/conf/config.yaml"
        ports:
        - containerPort: 4318 # OTLP HTTP
        - containerPort: 9090 # Prometheus endpoint
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-sender
  namespace: otel-sender
spec:
  type: ClusterIP
  selector:
    app: otel-collector-sender
  ports:
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: prometheus
    port: 9090
    targetPort: 9090
    protocol: TCP
