# filepath: /metrics-exporter/k8s-manifest.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-exporter
  namespace: metrics-exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-exporter
  template:
    metadata:
      labels:
        app: metrics-exporter
    spec:
      containers:
      - name: metrics-exporter
        image: metrics-exporter:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-exporter
  namespace: metrics-exporter
spec:
  type: ClusterIP
  selector:
    app: metrics-exporter
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP