services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped

  celery-exporter:
    image: ghcr.io/danihodovic/celery-exporter:e116052
    container_name: celery-exporter
    ports:
      - "9808:9808"
    command: --broker-url=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped