services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  webapp:
    image: ubaids/flask-redis-service:0.1
    container_name: flask-webapp
    ports:
      - "5000:5000"
    environment:
      - SERVICE_TYPE=web
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    image: ubaids/flask-redis-service:0.1
    container_name: celery-worker
    environment:
      - SERVICE_TYPE=worker
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - webapp
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped

  celery-exporter:
    image: ghcr.io/danihodovic/celery-exporter:e116052
    container_name: celery-exporter
    ports:
      - "9808:9808"
    command: --broker-url=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped