services:
  envoy:
    image: envoyproxy/envoy:v1.34-latest
    command:
      - "--log-level info"
      - "--config-path /etc/envoy/envoy.yaml"
    ports:
      - "5050:5050"
    volumes:
      - ./envoy/tls-route-to-service.yaml:/etc/envoy/envoy.yaml
      - ./certs/server.crt:/etc/certs/server.crt
      - ./certs/server.key:/etc/certs/server.key
    depends_on:
      - ui-service
  ui-service:
    image: ubaids/my-ui-service:latest
    ports:
      - "5000:5000"
